"""
SOFIA LUXURY STORY
CINEMATIC VERTICAL VIDEO CREATOR

Purpose:
Create original approximately 5-minute vertical mini-movies
with Sofia as the central character.

Output:
720 x 1280
9:16 vertical
24 FPS

Designed for:
- Luxury drama
- Action
- Romance
- Mystery
- Fantasy
- Adventure
- Billionaire stories
- Time travel
- Royal drama
- Thriller
- Supernatural stories

The video creator can use:
1. Story scenes generated by ScriptGenerator
2. Sofia reference-image generation
3. Pexels stock video
4. Voice-over
5. Background music
6. Cinematic movement
7. Subtitles
8. Professional transitions
"""

import os
import random
import requests
from pathlib import Path
from typing import Optional, List, Dict, Any

from loguru import logger
from dotenv import load_dotenv

from moviepy import (
    AudioFileClip,
    ImageClip,
    VideoFileClip,
    CompositeVideoClip,
    CompositeAudioClip,
    concatenate_videoclips,
    concatenate_audioclips,
    TextClip,
    ColorClip,
)

from moviepy.video.fx import FadeIn, FadeOut

from content.ai_image_gen import AIImageGenerator

load_dotenv()


class ProfessionalVideoCreator:
    """
    Creates Sofia Luxury Story cinematic vertical videos.
    """

    # ---------------------------------------------------------
    # DEFAULT PRODUCTION SETTINGS
    # ---------------------------------------------------------

    DEFAULT_RESOLUTION = (720, 1280)
    DEFAULT_FPS = 24

    MAX_SCENES = 12
    MIN_SCENES = 8

    def __init__(
        self,
        resolution=(720, 1280),
        fps=24
    ):
        self.resolution = resolution
        self.fps = fps

        self.width, self.height = resolution

        # Force portrait if an old caller sends landscape.
        if self.width >= self.height:
            logger.warning(
                "Old landscape resolution detected. "
                "Switching Sofia Luxury Story to 9:16 portrait."
            )

            self.resolution = self.DEFAULT_RESOLUTION
            self.width, self.height = self.resolution

        self.ai_image_gen = AIImageGenerator()

        self.pexels_key = os.getenv(
            "PEXELS_API_KEY"
        )

        # -----------------------------------------------------
        # SOFIA IDENTITY
        # -----------------------------------------------------

        self.sofia_identity = (
            "Sofia Luxury Story. "
            "Sofia is the central female protagonist and "
            "must remain visually recognizable throughout "
            "the entire movie. "
            "Elegant intelligent modern woman, "
            "consistent facial identity, "
            "cinematic realistic appearance, "
            "premium luxury aesthetic, "
            "high-end fashion, expressive eyes, "
            "natural skin texture, "
            "professional cinematic lighting, "
            "photorealistic movie still."
        )

        logger.info(
            f"🎬 Sofia Luxury Story renderer initialized "
            f"at {self.width}x{self.height} {self.fps}fps"
        )

    # =========================================================
    # MUSIC
    # =========================================================

    def _get_bg_music(
        self,
        mood: str = "luxury"
    ) -> str:

        possible = [
            mood,
            "luxury",
            "tech",
            "action",
            "drama",
        ]

        for selected in possible:

            path = Path(
                f"data/assets/bg_music_{selected}.mp3"
            )

            if path.exists():
                return str(path)

        return ""

    # =========================================================
    # STORY SCENE PREPARATION
    # =========================================================

    def _prepare_story_scenes(
        self,
        script_text: str,
        scenes: Optional[List[Dict[str, Any]]],
        total_duration: float,
        topic: str,
    ) -> List[Dict[str, Any]]:

        prepared = []

        # -----------------------------------------------------
        # USE STRUCTURED AI STORY SCENES WHEN AVAILABLE
        # -----------------------------------------------------

        if scenes:

            for index, scene in enumerate(
                scenes[:self.MAX_SCENES]
            ):

                if not isinstance(scene, dict):
                    continue

                location = str(
                    scene.get(
                        "location",
                        "luxury cinematic location"
                    )
                )

                action = str(
                    scene.get(
                        "action",
                        ""
                    )
                )

                emotion = str(
                    scene.get(
                        "emotion",
                        "determined"
                    )
                )

                visual_prompt = str(
                    scene.get(
                        "visual_prompt",
                        ""
                    )
                )

                narration = str(
                    scene.get(
                        "narration",
                        ""
                    )
                )

                dialogue = str(
                    scene.get(
                        "dialogue",
                        ""
                    )
                )

                description = " ".join(
                    [
                        location,
                        action,
                        emotion,
                        visual_prompt,
                    ]
                ).strip()

                prepared.append(
                    {
                        "scene_number": index + 1,
                        "location": location,
                        "action": action,
                        "emotion": emotion,
                        "visual_prompt": description,
                        "narration": narration,
                        "dialogue": dialogue,
                    }
                )

        # -----------------------------------------------------
        # FALLBACK: BUILD SCENES FROM SCRIPT
        # -----------------------------------------------------

        if not prepared:

            sentences = [
                s.strip()
                for s in script_text.replace(
                    "\n",
                    " "
                ).split(".")
                if len(s.strip()) > 20
            ]

            target = self._calculate_scene_count(
                total_duration
            )

            if not sentences:
                sentences = [
                    f"Sofia in a cinematic luxury scene "
                    f"related to {topic}"
                ]

            for index in range(target):

                sentence = sentences[
                    index % len(sentences)
                ]

                prepared.append(
                    {
                        "scene_number": index + 1,
                        "location": "cinematic luxury location",
                        "action": sentence,
                        "emotion": "determined",
                        "visual_prompt": sentence,
                        "narration": sentence,
                        "dialogue": "",
                    }
                )

        # -----------------------------------------------------
        # LIMIT SCENE COUNT
        # -----------------------------------------------------

        prepared = prepared[
            :self.MAX_SCENES
        ]

        if len(prepared) < self.MIN_SCENES:

            original = list(prepared)

            while len(prepared) < self.MIN_SCENES:

                source = original[
                    len(prepared) % len(original)
                ]

                duplicate = dict(source)

                duplicate[
                    "scene_number"
                ] = len(prepared) + 1

                prepared.append(
                    duplicate
                )

        # -----------------------------------------------------
        # DISTRIBUTE TIME
        # -----------------------------------------------------

        scene_duration = (
            total_duration / len(prepared)
        )

        for scene in prepared:

            scene["duration"] = max(
                8.0,
                scene_duration
            )

        return prepared

    # =========================================================
    # SCENE COUNT
    # =========================================================

    def _calculate_scene_count(
        self,
        duration: float
    ) -> int:

        if duration <= 90:
            return 8

        if duration <= 180:
            return 9

        if duration <= 270:
            return 10

        return 12

    # =========================================================
    # AI SCENE IMAGE
    # =========================================================

    def _generate_scene_image(
        self,
        scene: Dict[str, Any],
        index: int,
    ) -> str:

        output_dir = Path(
            "output/scene_images"
        )

        output_dir.mkdir(
            parents=True,
            exist_ok=True
        )

        visual = scene.get(
            "visual_prompt",
            ""
        )

        location = scene.get(
            "location",
            ""
        )

        action = scene.get(
            "action",
            ""
        )

        emotion = scene.get(
            "emotion",
            ""
        )

        prompt = (
            f"{self.sofia_identity} "
            f"Scene {index + 1}. "
            f"Sofia is actively present in this scene. "
            f"Location: {location}. "
            f"Action: {action}. "
            f"Emotion: {emotion}. "
            f"Visual direction: {visual}. "
            "The same Sofia character must be recognizable. "
            "Cinematic movie frame, "
            "strong composition, "
            "dramatic depth, "
            "professional lighting, "
            "realistic environment, "
            "premium production design, "
            "natural anatomy, "
            "no text, "
            "no watermark, "
            "vertical 9:16 composition."
        )

        try:

            logger.info(
                f"🎨 Generating Sofia cinematic scene "
                f"{index + 1}"
            )

            return self.ai_image_gen.generate_image(
                prompt=prompt,
                style="realistic cinematic",
                width=self.width,
                height=self.height,
                filename=(
                    f"sofia_movie_scene_"
                    f"{index + 1:03d}.jpg"
                ),
                use_reference=True,
            )

        except TypeError:

            # Compatibility with older AIImageGenerator
            try:

                return self.ai_image_gen.generate_image(
                    prompt=prompt,
                    style="realistic cinematic",
                    width=self.width,
                    height=self.height,
                    filename=(
                        f"sofia_movie_scene_"
                        f"{index + 1:03d}.jpg"
                    ),
                )

            except Exception as e:

                logger.warning(
                    f"AI scene generation failed: {e}"
                )

        except Exception as e:

            logger.warning(
                f"AI scene generation failed: {e}"
            )

        return ""

    # =========================================================
    # PEXELS SEARCH
    # =========================================================

    def _search_stock_videos(
        self,
        query: str,
        count: int = 3
    ) -> list:

        if not self.pexels_key:
            return []

        try:

            response = requests.get(
                "https://api.pexels.com/videos/search",
                headers={
                    "Authorization": self.pexels_key
                },
                params={
                    "query": query,
                    "per_page": min(
                        count,
                        10
                    ),
                    "orientation": "portrait",
                },
                timeout=20,
            )

            if response.status_code != 200:

                logger.warning(
                    f"Pexels status: "
                    f"{response.status_code}"
                )

                return []

            videos = response.json().get(
                "videos",
                []
            )

            logger.info(
                f"📹 Pexels found "
                f"{len(videos)} portrait videos "
                f"for '{query}'"
            )

            return videos

        except Exception as e:

            logger.warning(
                f"Pexels search failed: {e}"
            )

            return []

    # =========================================================
    # DOWNLOAD PEXELS VIDEO
    # =========================================================

    def _download_stock_video(
        self,
        video_data: dict,
        path: str
    ) -> bool:

        try:

            files = video_data.get(
                "video_files",
                []
            )

            if not files:
                return False

            candidates = []

            for item in files:

                link = item.get(
                    "link"
                )

                width = int(
                    item.get(
                        "width",
                        0
                    )
                )

                height = int(
                    item.get(
                        "height",
                        0
                    )
                )

                if not link:
                    continue

                if height > width:

                    candidates.append(
                        (
                            width * height,
                            item
                        )
                    )

            if not candidates:

                for item in files:

                    link = item.get(
                        "link"
                    )

                    if link:

                        candidates.append(
                            (
                                int(
                                    item.get(
                                        "width",
                                        0
                                    )
                                )
                                *
                                int(
                                    item.get(
                                        "height",
                                        0
                                    )
                                ),
                                item
                            )
                        )

            if not candidates:
                return False

            candidates.sort(
                key=lambda x: x[0],
                reverse=True
            )

            selected = candidates[0][1]

            response = requests.get(
                selected["link"],
                timeout=45
            )

            if response.status_code != 200:

                return False

            Path(path).parent.mkdir(
                parents=True,
                exist_ok=True
            )

            with open(
                path,
                "wb"
            ) as file:

                file.write(
                    response.content
                )

            return True

        except Exception as e:

            logger.warning(
                f"Stock download failed: {e}"
            )

            return False

    # =========================================================
    # FIT IMAGE TO 9:16
    # =========================================================

    def _create_image_clip(
        self,
        image_path: str,
        duration: float,
    ):

        try:

            clip = ImageClip(
                image_path,
                duration=duration
            )

            # Scale so the entire vertical frame is filled.
            scale_w = (
                self.width / clip.w
            )

            scale_h = (
                self.height / clip.h
            )

            scale = max(
                scale_w,
                scale_h
            )

            clip = clip.resized(
                scale
            )

            clip = clip.cropped(
                x_center=clip.w / 2,
                y_center=clip.h / 2,
                width=self.width,
                height=self.height
            )

            return clip

        except Exception as e:

            logger.warning(
                f"Image clip failed: {e}"
            )

            return ColorClip(
                size=self.resolution,
                color=(12, 12, 16),
                duration=duration
            )

    # =========================================================
    # STOCK CLIP TO 9:16
    # =========================================================

    def _create_stock_clip(
        self,
        video_path: str,
        duration: float
    ):

        try:

            clip = VideoFileClip(
                video_path
            )

            if clip.duration <= 0:
                clip.close()
                return None

            # Choose a random section if longer.
            if clip.duration > duration:

                max_start = max(
                    0,
                    clip.duration - duration
                )

                start = random.uniform(
                    0,
                    max_start
                )

                clip = clip.subclipped(
                    start,
                    start + duration
                )

            else:

                # Loop short clips safely.
                repeats = int(
                    duration / clip.duration
                ) + 1

                parts = []

                for _ in range(
                    repeats
                ):

                    parts.append(
                        VideoFileClip(
                            video_path
                        )
                    )

                clip = concatenate_videoclips(
                    parts,
                    method="compose"
                ).subclipped(
                    0,
                    duration
                )

            # Fit portrait.
            scale_w = (
                self.width / clip.w
            )

            scale_h = (
                self.height / clip.h
            )

            scale = max(
                scale_w,
                scale_h
            )

            clip = clip.resized(
                scale
            )

            clip = clip.cropped(
                x_center=clip.w / 2,
                y_center=clip.h / 2,
                width=self.width,
                height=self.height
            )

            return clip

        except Exception as e:

            logger.warning(
                f"Stock clip failed: {e}"
            )

            return None

    # =========================================================
    # CINEMATIC MOVEMENT
    # =========================================================

    def _add_cinematic_movement(
        self,
        clip,
        duration: float,
        direction: int
    ):

        # Keep movement lightweight.
        # MoviePy performs the final transformation during render.

        try:

            if not isinstance(
                clip,
                ImageClip
            ):
                return clip

            # Very subtle zoom.
            start_scale = 1.02
            end_scale = 1.07

            def resize_function(t):

                if duration <= 0:
                    return start_scale

                progress = min(
                    1.0,
                    max(
                        0.0,
                        t / duration
                    )
                )

                if direction % 2 == 0:

                    return (
                        start_scale
                        +
                        (
                            end_scale
                            - start_scale
                        )
                        * progress
                    )

                return (
                    end_scale
                    -
                    (
                        end_scale
                        - start_scale
                    )
                    * progress
                )

            return clip.resized(
                lambda t: resize_function(t)
            )

        except Exception as e:

            logger.debug(
                f"Movement skipped: {e}"
            )

            return clip

    # =========================================================
    # SUBTITLE
    # =========================================================

    def _make_subtitle(
        self,
        text: str,
        duration: float
    ):

        if not text:
            return None

        try:

            text = text.strip()

            if len(text) > 140:
                text = text[:137] + "..."

            subtitle = TextClip(
                text=text,
                font_size=38,
                color="white",
                stroke_color="black",
                stroke_width=3,
                size=(
                    self.width - 80,
                    180
                ),
                method="caption",
            )

            subtitle = (
                subtitle
                .with_position(
                    (
                        "center",
                        self.height - 230
                    )
                )
                .with_duration(
                    duration
                )
            )

            return subtitle

        except Exception as e:

            logger.warning(
                f"Subtitle failed: {e}"
            )

            return None

    # =========================================================
    # SCENE TRANSITION
    # =========================================================

    def _apply_transition(
        self,
        clip,
        index: int
    ):

        try:

            effects = []

            if index == 0:

                effects.append(
                    FadeIn(0.6)
                )

            else:

                effects.append(
                    FadeIn(0.35)
                )

            if index > 0:

                effects.append(
                    FadeOut(0.25)
                )

            if effects:

                clip = clip.with_effects(
                    effects
                )

        except Exception:
            pass

        return clip

    # =========================================================
    # MAIN VIDEO CREATOR
    # =========================================================

    def create_professional_video(
        self,
        voiceover_path: str,
        topic: str,
        script_text: str = "",
        niche: str = "luxury",
        style: str = "cinematic",
        add_music: bool = True,
        output_path: str = (
            "output/sofia_luxury_story.mp4"
        ),
        scenes: Optional[
            List[Dict[str, Any]]
        ] = None,
    ) -> str:

        logger.info(
            f"🎬 Creating Sofia Luxury Story: "
            f"{str(topic)[:100]}"
        )

        voice_path = Path(
            voiceover_path
        )

        if not voice_path.exists():

            logger.error(
                f"Voiceover not found: "
                f"{voiceover_path}"
            )

            return ""

        # -----------------------------------------------------
        # AUDIO
        # -----------------------------------------------------

        audio = None
        final_video = None
        video_clips = []

        try:

            audio = AudioFileClip(
                str(voice_path)
            )

            total_duration = float(
                audio.duration
            )

            logger.info(
                f"⏱️ Voice-over duration: "
                f"{total_duration:.1f}s"
            )

            # -------------------------------------------------
            # STORY SCENES
            # -------------------------------------------------

            story_scenes = (
                self._prepare_story_scenes(
                    script_text=script_text,
                    scenes=scenes,
                    total_duration=total_duration,
                    topic=str(topic),
                )
            )

            logger.info(
                f"🎬 Using "
                f"{len(story_scenes)} cinematic scenes"
            )

            # -------------------------------------------------
            # PEXELS SEARCH
            # -------------------------------------------------

            stock_results = []

            if self.pexels_key:

                search_terms = [
                    "luxury woman",
                    "luxury hotel",
                    "luxury car",
                    "luxury city night",
                    "private jet",
                    "luxury yacht",
                    "fashion woman",
                    "cinematic woman",
                    "action woman",
                    "luxury mansion",
                ]

                for term in search_terms:

                    found = (
                        self._search_stock_videos(
                            term,
                            count=2
                        )
                    )

                    stock_results.extend(
                        found
                    )

                    if len(
                        stock_results
                    ) >= len(
                        story_scenes
                    ):

                        break

            # -------------------------------------------------
            # CREATE EACH SCENE
            # -------------------------------------------------

            for index, scene in enumerate(
                story_scenes
            ):

                duration = float(
                    scene.get(
                        "duration",
                        total_duration
                        /
                        len(story_scenes)
                    )
                )

                clip = None

                # ---------------------------------------------
                # USE STOCK ONLY WHEN IT FITS THE STORY
                # ---------------------------------------------

                if stock_results:

                    stock_data = (
                        stock_results[
                            index
                            %
                            len(stock_results)
                        ]
                    )

                    stock_path = Path(
                        "output/scene_images"
                    ) / (
                        f"stock_scene_"
                        f"{index + 1:03d}.mp4"
                    )

                    if self._download_stock_video(
                        stock_data,
                        str(stock_path)
                    ):

                        clip = (
                            self._create_stock_clip(
                                str(stock_path),
                                duration
                            )
                        )

                # ---------------------------------------------
                # AI SOFIA SCENE
                # ---------------------------------------------

                # Prefer Sofia AI scenes for the majority
                # of the movie. This keeps Sofia central.
                if index % 3 != 1 or clip is None:

                    image_path = (
                        self._generate_scene_image(
                            scene,
                            index
                        )
                    )

                    if image_path:

                        clip = (
                            self._create_image_clip(
                                image_path,
                                duration
                            )
                        )

                        clip = (
                            self._add_cinematic_movement(
                                clip,
                                duration,
                                index
                            )
                        )

                # ---------------------------------------------
                # FALLBACK
                # ---------------------------------------------

                if clip is None:

                    clip = ColorClip(
                        size=self.resolution,
                        color=(
                            10,
                            10,
                            14
                        ),
                        duration=duration
                    )

                # ---------------------------------------------
                # SUBTITLE
                # ---------------------------------------------

                subtitle_text = (
                    scene.get(
                        "dialogue"
                    )
                    or scene.get(
                        "narration"
                    )
                    or ""
                )

                subtitle = (
                    self._make_subtitle(
                        subtitle_text,
                        duration
                    )
                )

                if subtitle:

                    clip = CompositeVideoClip(
                        [
                            clip,
                            subtitle
                        ],
                        size=self.resolution
                    )

                # ---------------------------------------------
                # TRANSITION
                # ---------------------------------------------

                clip = (
                    self._apply_transition(
                        clip,
                        index
                    )
                )

                video_clips.append(
                    clip
                )

                logger.info(
                    f"🎞️ Scene "
                    f"{index + 1}/"
                    f"{len(story_scenes)} ready"
                )

            # -------------------------------------------------
            # COMBINE
            # -------------------------------------------------

            logger.info(
                "🎞️ Combining Sofia cinematic scenes..."
            )

            final_video = (
                concatenate_videoclips(
                    video_clips,
                    method="compose"
                )
            )

            # Match audio duration.
            if final_video.duration > total_duration:

                final_video = (
                    final_video
                    .subclipped(
                        0,
                        total_duration
                    )
                )

            # -------------------------------------------------
            # VOICEOVER
            # -------------------------------------------------

            final_video = (
                final_video
                .with_audio(audio)
            )

            # -------------------------------------------------
            # BACKGROUND MUSIC
            # -------------------------------------------------

            if add_music:

                music_path = (
                    self._get_bg_music(
                        "luxury"
                    )
                )

                if music_path:

                    music = None

                    try:

                        music = AudioFileClip(
                            music_path
                        )

                        # Loop music if necessary.
                        if music.duration < total_duration:

                            repeat_count = (
                                int(
                                    total_duration
                                    /
                                    music.duration
                                )
                                + 1
                            )

                            music_parts = []

                            for _ in range(
                                repeat_count
                            ):

                                music_parts.append(
                                    AudioFileClip(
                                        music_path
                                    )
                                )

                            music = (
                                concatenate_audioclips(
                                    music_parts
                                )
                            )

                        music = (
                            music
                            .subclipped(
                                0,
                                total_duration
                            )
                            .with_volume_scaled(
                                0.06
                            )
                        )

                        final_audio = (
                            CompositeAudioClip(
                                [
                                    audio,
                                    music
                                ]
                            )
                        )

                        final_video = (
                            final_video
                            .with_audio(
                                final_audio
                            )
                        )

                        logger.info(
                            "🎵 Cinematic background "
                            "music added."
                        )

                    except Exception as e:

                        logger.warning(
                            f"Music failed: {e}"
                        )

                    finally:

                        try:

                            if music:
                                music.close()

                        except Exception:
                            pass

            # -------------------------------------------------
            # TITLE
            # -------------------------------------------------

            try:

                title = TextClip(
                    text="SOFIA LUXURY STORY",
                    font_size=52,
                    color="white",
                    stroke_color="black",
                    stroke_width=3,
                    size=(
                        self.width - 80,
                        100
                    ),
                    method="caption",
                )

                title = (
                    title
                    .with_position(
                        (
                            "center",
                            80
                        )
                    )
                    .with_duration(
                        min(
                            3.5,
                            total_duration
                        )
                    )
                    .with_effects(
                        [
                            FadeIn(0.4),
                            FadeOut(0.6)
                        ]
                    )
                )

                final_video = (
                    CompositeVideoClip(
                        [
                            final_video,
                            title
                        ],
                        size=self.resolution
                    )
                )

            except Exception as e:

                logger.warning(
                    f"Title overlay failed: {e}"
                )

            # -------------------------------------------------
            # OUTPUT
            # -------------------------------------------------

            output = Path(
                output_path
            )

            output.parent.mkdir(
                parents=True,
                exist_ok=True
            )

            logger.info(
                "🚀 Rendering final "
                "Sofia Luxury Story..."
            )

            final_video.write_videofile(
                str(output),
                fps=self.fps,
                codec="libx264",
                audio_codec="aac",
                bitrate="4500k",
                preset="veryfast",
                threads=2,
                logger=None,
            )

            # -------------------------------------------------
            # VERIFY
            # -------------------------------------------------

            if output.exists():

                size_mb = (
                    output.stat().st_size
                    /
                    (1024 * 1024)
                )

                logger.info(
                    f"✅ SOFIA LUXURY STORY CREATED "
                    f"({size_mb:.1f} MB)"
                )

                return str(output)

            logger.error(
                "❌ Final video file was not created."
            )

            return ""

        except Exception as e:

            logger.exception(
                f"❌ Sofia video creation failed: {e}"
            )

            return ""

        finally:

            # -------------------------------------------------
            # CLEANUP
            # -------------------------------------------------

            try:

                if final_video:
                    final_video.close()

            except Exception:
                pass

            try:

                if audio:
                    audio.close()

            except Exception:
                pass

            for clip in video_clips:

                try:
                    clip.close()

                except Exception:
                    pass


# =============================================================
# TEST
# =============================================================

if __name__ == "__main__":

    print(
        "\n"
        + "=" * 65
    )

    print(
        "🎬 SOFIA LUXURY STORY "
        "VERTICAL VIDEO CREATOR"
    )

    print(
        "=" * 65
    )

    creator = ProfessionalVideoCreator()

    print(
        f"\nResolution: "
        f"{creator.width}x{creator.height}"
    )

    print(
        f"Aspect ratio: "
        f"{creator.width / creator.height:.3f}"
    )

    print(
        f"FPS: "
        f"{creator.fps}"
    )

    print(
        "\nReady for Sofia cinematic "
        "vertical story production."
    )
